// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbp7hVQA1nRR8h3WiyClNUxkNijXyjN9o',
    appId: '1:937942745156:web:82a26b800abe2518573c11',
    messagingSenderId: '937942745156',
    projectId: 'smartshop-1f548',
    authDomain: 'smartshop-1f548.firebaseapp.com',
    storageBucket: 'smartshop-1f548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Ks4iaxJohSb7eHgKrsfQWTe_iCTFb_8',
    appId: '1:937942745156:android:15d24feb2aa60406573c11',
    messagingSenderId: '937942745156',
    projectId: 'smartshop-1f548',
    storageBucket: 'smartshop-1f548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC010-NyghZOIYEKyvyu7Dxb2jgrtwYSi8',
    appId: '1:937942745156:ios:14ad832b4445b776573c11',
    messagingSenderId: '937942745156',
    projectId: 'smartshop-1f548',
    storageBucket: 'smartshop-1f548.appspot.com',
    iosBundleId: 'com.example.smartshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC010-NyghZOIYEKyvyu7Dxb2jgrtwYSi8',
    appId: '1:937942745156:ios:fe018a736f0b68d8573c11',
    messagingSenderId: '937942745156',
    projectId: 'smartshop-1f548',
    storageBucket: 'smartshop-1f548.appspot.com',
    iosBundleId: 'com.example.smartshop.RunnerTests',
  );
}
